main.go
tmpl.go

This adds the BSD license header used by many Go projects (Go, Upspin, etc)
> Copyright {{.Year}} {{.Holder}}. All rights reserved.
Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file.

Add bsd license header

---

main.go

As per OSPO, this is the new default name for Google copyright ownership.

Change default copyright holder to Google LLC

---

testdata/expected/file.c
testdata/expected/file.cc
testdata/expected/file.cpp
testdata/expected/file.cs
testdata/expected/file.css
testdata/expected/file.dart
testdata/expected/file.el
testdata/expected/file.erl
testdata/expected/file.go
testdata/expected/file.h
testdata/expected/file.hh
testdata/expected/file.hpp
testdata/expected/file.hs
testdata/expected/file.html
testdata/expected/file.java
testdata/expected/file.js
testdata/expected/file.lisp
testdata/expected/file.m
testdata/expected/file.mm
testdata/expected/file.php
testdata/expected/file.proto
testdata/expected/file.py
testdata/expected/file.rs
testdata/expected/file.scala
testdata/expected/file.swift
testdata/expected/file.tf
testdata/expected/file.xml
testdata/expected/file1.sh
testdata/expected/file2.sh
tmpl.go

If a license text had blank lines, they would result in a trailing
whitespace when prefixed with the line comments.
This change removes trailing whitespace from the middle lines,
leaving top and bottom as is.
Fixes #10
/cc @morgante

Trim trailing whitespace

---

main.go
testdata/expected/file2.xml
testdata/initial/file2.xml

Keep `<?xml` and `<!doctype` declarations.
Fixes #5.

Better support for XML and HTML

---

main.go
tmpl.go

Picking up #1  to be able to read a license template from a file for more versatility.

Read license from file (take 2)

---

main.go
main_test.go
testdata/multiyear_file.c
tmpl.go

This effectively allows for arbitrary copyright years. For instance, 2018-2019.
Based on #18.
Fixes #17.
/cc @cryptocode

Switch year arg from int to string

---

main.go

We would love to be able to use your tool for Kotlin files. The most common file extension are .kt for regular modules and .kts for scripts.

Add kotlin files to list of accepted extensions

---

main.go

Adds the -v option which prints the name of the files that have been modified.

Add verbose option to print filename when modified

---

.travis.yml
README.md
go.mod
go.sum
main.go
main_test.go

Implement `-check` flag and exit codes

---

main.go
testdata/expected/file.php
testdata/initial/file.php

Looking at https://www.php.net/manual/en/language.basic-syntax.phptags.php
there are just too many variations and I'm not convinced the added
complexity to support all of them would be worth it here.
Thus, support only the case where closing tag "?>" is either omitted
or on a separate line. A workaround for all other cases is to add
the license header manually.
Can always revisit this later.
Closes https://github.com/google/addlicense/issues/30.

Update .php handling to keep <?php at the top

---

README.md
main.go
main_test.go
tmpl.go

Adds support for generating MPL license headers.
Includes one additional test.
Updated README to include `mpl` option also.
@x1ddos

MPL license support

---

main.go
testdata/expected/file.cjs
testdata/expected/file.mjs
testdata/initial/file.cjs
testdata/initial/file.mjs

Many JavaScript packages support the `.mjs` and `.cjs` JavaScript file extensions.
For example, a popular JavaScript testing library, [ava](https://github.com/avajs/ava), [allows an `ava.config.cjs` JavaScript file](https://github.com/avajs/ava/blob/master/docs/06-configuration.md#avaconfigcjs) . It also supports other file extensions, but `.cjs` indicates it's a CommonJS module.
Babel also [supports `.mjs` and `.cjs`](https://babeljs.io/docs/en/config-files#supported-file-extensions).

Add support for .mjs and .cjs JavaScript file extensions

---

main.go
testdata/expected/file_generated.bzl
testdata/initial/file_generated.bzl

Broken by #45.
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Skip .bzl files generated by cargo raze.

---

Dockerfile
README.md

Hi,
Please review and consider merging this PR which adds Docker support to addlicense.
Thanks,
Rotem

Add Docker support.

---

main.go

This PR adds the feature to skip extensions or files to be checked or add the license header.
In some cases, we don't want to add the headers for some files, and will be useful if we can just skip those.
After I did the implementation I saw the PR: https://github.com/google/addlicense/pull/73
If the maintainers prefer the other approach I'm fine and we can close this PR

Skip extensions or files

---

main.go
testdata/custom.tpl
tmpl.go
tmpl_test.go

This PR implements the changes described in https://github.com/google/addlicense/pull/77#issuecomment-886240907.  This contains two commits, which might be easier to review individually.  The first is just a refactor and slight cleanup of existing code with no change in behavior.  These changes make it easier to add SPDX support as well as begin to decouple certain logic to make testing simpler.  The second commit actually adds support for SPDX headers as discussed in #77.
Closes #77

Add support for SPDX style headers

---

Dockerfile
README.md

Use go modules instead of dep.  Use two stage build to build a minimal (4 MB) application image.
Fixes #51 #71 #78

fix building docker image

---

.github/workflows/tests.yaml
README.md
go.mod
go.sum
main.go
main_test.go

use the [doublestar library](https://github.com/bmatcuk/doublestar) to support pattern matching of files or directories to ignore. This replaces (and deprecates) the previous `-skip` flag which only supported file extensions.
(previous discussion in https://github.com/google/addlicense/pull/70#issuecomment-888695051)
The doublestar library requires go1.16, so I'm leaving this is draft mode until go1.17 is released (which should be any day now).
/cc @Shikugawa @laurentsimon @Shabirmean @lukehinds @cpanato - you've all been involved in similar implementations in #70, #73, and #75, so I'm curious if this implementation meets your use cases.

support ignoring file or directories

---

README.md

I don't *love* using `ghcr.io/google/addlicense` even for the local build instructions (rather than just `google/addlicense`), but it does make the later instructions to test and run the image consistent.  At the end of the day, probably not a big deal.

docs: update docker instructions to include GitHub container registry

---

main.go
main_test.go

Add support for cmake files, adapted from #67
Slight refactoring in `licenseHeader()` and `fileExtension()` to make this and other future logic for determining license comment prefix a little cleaner.
Closes #67

add support for cmake files

---

README.md
main.go

This PR changes the default behavior of logging all skipped files to instead logging the skipped files only in verbose mode (with `-v` flag). 
When a ton of files are skipped (e.g. `-ignore vendor/**`) then the output of `addlicense` becomes quite verbose and the actual output which we are interested in, i.e. which files were modified or which files are missing license info when `-check` is used, gets buried in between the `skipping` log lines.
P.S. I have also updated the usage instructions in the README with the up-to-date flag information as per `addlicense --help`.

Only log skipped files in verbose mode

---

tmpl.go
tmpl_test.go

Also ensures SPDX holder is outputed when year isn't set
Fixes #36

Don't render extra space when year is not set

---

main.go
main_test.go

Note: The file names are lower-cased before triggering a comparison.
This requires that we use lower case 'build' when performing comparisons

Add support for bazel BUILD files

---

.github/workflows/linter.yaml
main.go
main_test.go
testdata/expected/file.tf

Hashicorp documentation references using hash (`#`) as the default comment and is generally preferred to the long block comment style.
https://developer.hashicorp.com/terraform/language/syntax/configuration#comments

update terraform to use hash as comment per recommended guidelines 

---

README.md

The default for `year` is actually the current year, so this will update the documentation to reflect that

fix(readme): Update the docs to show current year

---

main.go
testdata/expected/file.toml
testdata/initial/file.toml

This is used in many contexts, including being the format used by Cargo, the Rust package manager.

Add support for TOML configuration files

---

main.go

bazel build files for external repos -- eg. used in conjunction with `http_archive` -- are often named `<repo>.BUILD`

Support *.BUILD files

---

.pre-commit-hooks.yaml
README.md

Hi guys,
great tool. I have looked around and this tool is exactly what i am looking for.
I would like to use your tool in combination with pre-commit. The cool thing is then to run your tool during git hooks.
I have seen that for example the project golangci-lint also provide this pre-commit integration.
https://github.com/golangci/golangci-lint/blob/master/.pre-commit-hooks.yaml
If you have questions, feel free to ask me.
Kind Regards,
Thomy90

feature: add pre-commit support

---

main.go
main_test.go

Although not as prevalent as they used to be, we still have some `.htm` files (otherwise identical to HTML), so I figured I'd add support for those, too.

feat: add support for .htm files

---

main.go

`fileMatches` will receive paths with native path separators(i.e. `\` on Windows). Per the [doc](https://github.com/bmatcuk/doublestar/tree/v4?tab=readme-ov-file#match) `doublestar.Match` doesn't work as expected with `\`, and `filepath.ToSlash()` should be used to handle such case.

Fix ignore on Windows

---

main.go
main_test.go

This adds support for the `.ru` extension, which is idiomatically used for `config.ru` files in the Rack ruby framework. This specifically requires adding an additional element to the `head` slice for `#\` directives.
I added a test explicitly for validating the intact header is left in.
More information on the file format itself can be found [here](https://github.com/rack/rack/wiki/(tutorial)-rackup-howto).

Add support for Rackup (.ru) config files

---

main.go
main_test.go
testdata/expected/file.graphql
testdata/initial/file.graphql

This PR adds support for `.graphql` files.
[As stated](https://dgraph.io/docs/graphql/schema/documentation/), GraphQL files support `#` comments, so this PR just adds `.graphql` to the already existing list of files that use this type of comments.
This is my first time writing a Golang code, it is not tested. However, it seems straightforward, so I'm sure it works.
CLA is signed.

Add `.graphql` support

---

tmpl.go
tmpl_test.go

As per the title. All middle prefixes are no more than 3 characters. This PR wraps the MIT License template to a width of 77 to ensure the generated license fits into 80 characters.
Before:
After:

Wrap the MIT License template to ensure the generated license fits into 80 characters
